discourse_poison_fountain:
  poison_fountain_enabled:
    default: false
  poison_fountain_source:
    default: https://rnsaffn.com/poison2/
  poison_fountain_textual_only:
    default: true
  poison_fountain_force_plain_text:
    default: true
  poison_fountain_update_robots_txt:
    default: true
  poison_fountain_cache_hours:
    default: 6
    min: 1
    max: 24
  poison_fountain_entries:
    default: 10
    min: 1
  poison_fountain_link_count:
    default: 1
    min: 1
